chats/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('', views.chat_view, name="chat_view"),
    path('<str:who>/', views.chat_with, name="chat_with"),

]

versity_cr_manage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('chat/', include('chats.urls')),
]

#  --------- ADDED THIS FOR LOAD MEDIA --------------

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns+= staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# -------------------------------------------------------

common/models.py
from django.db import models
import uuid
from django.core.exceptions import ValidationError

from users.models import Intakes, Sections, Departments,Student


class CommonBaseModel(models.Model):
    uid = models.UUIDField(primary_key=True, default= uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class UpcomingExams(CommonBaseModel):
    intake = models.ForeignKey(Intakes, on_delete=models.CASCADE)
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)
    section = models.ForeignKey(Sections, on_delete=models.CASCADE)
    exam_name = models.CharField(max_length=10, choices=[('Class Test', 'Class Test'),('Quiz Test', 'Quiz Test'),('Mid Term', 'Mid Term'),('Final Test', 'Final Test')])
    course_name = models.CharField( max_length=50)
    course_code = models.CharField( max_length=7)
    date = models.DateField(auto_now=False, auto_now_add=False)
    topic = models.CharField(max_length=150)
    detail = models.TextField()

    def __str__(self) -> str:
        return f"{self.course_code} - {self.exam_name}"
    
DAYS = [
    ('sat','SAT'),
    ('sun','SUN'),
    ('mon','MON'),
    ('tue','TUE'),
    ('wed','WED'),
    ('thu','THU'),
    ('fri','FRI'),
]

TIMES = [
("08:00AMto09:15AM","08:00 AM to 09:15 AM"),
("09:15AMto10:30AM","09:15 AM to 10:30 AM"),
("10:30AMto11:45AM","10:30 AM to 11:45 AM"),
("11:45AMto01:00PM","11:45 AM to 01:00 PM"),
("01:30PMto02:45PM","01:30 PM to 02:45 PM"),
("02:45PMto04:00PM","02:45 PM to 04:00 PM"),
("04:00PMto05:15PM","04:00 PM to 05:15 PM"),
("05:15PMto06:30PM","05:15 PM to 06:30 PM"),
]

class ClassRoutine(CommonBaseModel):
    day = models.CharField( max_length=5, choices=DAYS)
    time = models.CharField( max_length=100, choices=TIMES)
    course_code = models.CharField( max_length=8)
    faculty_short_name = models.CharField(max_length=5)
    building = models.PositiveIntegerField()
    room = models.PositiveIntegerField()

    intake = models.ForeignKey(Intakes, on_delete=models.CASCADE)
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)
    section = models.ForeignKey(Sections, on_delete=models.CASCADE)

    def __str__(self):
        return self.course_code
    # METHOD - 01 -->>
    class Meta:
        unique_together = (('day', 'time', 'intake', 'department', 'section'),)


    # METHOD - 02 -->>
    # def save(self, *args, **kwargs):
    #     # Check if there's an existing routine with the same day, time, intake, department, and section
    #     existing_routine = ClassRoutine.objects.filter(
    #         day=self.day,
    #         time=self.time,
    #         intake=self.intake,
    #         department=self.department,
    #         section=self.section
    #     ).exists()
        
    #     if existing_routine:
    #         raise ValidationError("A routine with the same day and time already exists for this intake, department, and section.")
        
        # super().save(*args, **kwargs)


TYPES = [
    ('assignment', 'Assignment'),
    ('lab_report', 'Lab Report'),
    ('presentation', 'Peresentation'),

]

class Assignments(CommonBaseModel):
    types = models.CharField(max_length=50, choices=TYPES, default='assignment')
    course_code = models.CharField( max_length=8)
    course_title = models.CharField( max_length=100)
    assignment_title = models.CharField(max_length=150)
    detail = models.TextField()
    date = models.DateField( auto_now=False, auto_now_add=False, null=True, blank=True)

    intake = models.ForeignKey(Intakes, on_delete=models.CASCADE, null=True, blank=True)
    department = models.ForeignKey(Departments, on_delete=models.CASCADE, null=True, blank=True)
    section = models.ForeignKey(Sections, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.assignment_title
    
class Announcements(CommonBaseModel):
    announcement = models.CharField(max_length=500)
    image = models.ImageField(upload_to="Announcements", null=True, blank=True)
    file = models.FileField(upload_to="Announcements", null=True, blank=True)

    who_posted = models.ForeignKey(Student, on_delete=models.CASCADE)
    
    intake = models.ForeignKey(Intakes, on_delete=models.CASCADE)
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)
    section = models.ForeignKey(Sections, on_delete=models.CASCADE)


    def __str__(self) -> str:
        return f"{self.announcement}"

templates/pages/add_announcement.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Add Announcement{% endblock title %}
{% block css %}
		
{% endblock css %}
{% block content %}
    <div class="card m-0">
        <div class="card-header">
            <div class="card-title">Add new announcement </div>
        </div>
        <div class="card-body">
            {% include "pages/only_form.html" %}
        </div>
    </div>
{% endblock content %}

templates/pages/add_assignments.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Add Assignment{% endblock title %}
{% block css %}
		
{% endblock css %}
{% block content %}
    <div class="card m-0">
        <div class="card-header">
            <div class="card-title">Add new assignment or report's notice </div>
        </div>
        <div class="card-body">
            {% include "pages/only_form.html" %}
        </div>
    </div>
{% endblock content %}

templates/pages/add_routine.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Add Routine{% endblock title %}
{% block css %}
		
{% endblock css %}
{% block content %}
<div class="row gutters">
    {% if user.role == 'cr' or user.is_superuser %}
    <div class=" col-md-4 ">
        {% include "pages/only_form.html" %}
    </div>
    
    {% else %}
    
    {% endif %}
    <div class="col-md-8">
        {% include "pages/only_routine.html" %}
    </div>
</div>




{% endblock content %}

templates/pages/all_announcement.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Announcements{% endblock title %}
{% block css %}
<style>
    .bg-for-you {
      background-color: #d9eee1;
    }
</style>
{% endblock css %}
{% block content %}

<div class="row gutters justify-content-center"> 
    <h4>--- ANNOUNCEMENTS ---</h4>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        {% if user.role == 'cr' %}
        <div class="text-right mb-4">
            <a href="{% url "add_announcement" %}" class="btn btn-primary" >+ Add New Announcement</a>
        </div>
        {% endif %}
    </div>
    <div class="col-md-12 col-12  subscribe-form">
        <div class="customScroll5 mt-0 mb-0">
            <ul class="user-messages">
                {% for announce in announcements %}
                <li class="clearfix bg-for-you rounded p-2">
                    <div class="customer"><img src="{{announce.who_posted.image.url}}" alt="pic"></div>
                    <div class="delivery-details ">
                        <span class="badge badge-primary">{{announce.who_posted}}</span>
                        <span class="badge badge-info">{{announce.created_at}}</span>
                        <p>{{announce.announcement}}</p>
                
                            <div class="row gutters">
                                {% if announce.image %}
                                <div class="col-xl-2 col-lg-2 col-md-3 col-sm-4 col-6">
                                    <a href="{{announce.image.url}}" class="effects">
                                        <img src="{{announce.image.url}}" class="img-fluid" alt="pic">
                                    </a>
                                </div>
                                {% endif %}
                            </div>
            
                    </div>
                </li>                       
                {% endfor %}
            </ul>
        </div>            
    </div>
    
</div>

{% endblock content %}

{% block js %}

<script src="{% static "vendor/slimscroll/slimscroll.min.js" %}"></script>
<script src="{% static "vendor/slimscroll/custom-scrollbar.js" %}"></script>

{% endblock js %}

templates/pages/all_cr.html
{% extends "base/base.html" %}
{% load static %}
{% load custom_tags %}
{% block title %}All CRs'{% endblock title %}
{% block css %}

{% endblock css %}
{% block content %}

<div class="table-container">
    <div class="row">
        <div class="col-sm-12 col-md-12 d-flex justify-content-center"> 
            <form class="d-flex flex-wrap align-items-center mb-2">
                {% for field in search_option.form %}
                <div class="form-group mb-2 me-2 d-flex align-items-center">
                    <label class="text-dark ml-2 mr-2">{{ field.label }} </label> 
                    {{ field|add_class:"form-control" }}
                </div>
                {% endfor %}
                <button class="btn btn-primary mb-2 ml-2" type="submit"><i class="icon-search1"></i></button>

            </form> 
        </div>
    </div>
    
      
    <div class="table-responsive">
        
        <table class="table custom-table m-0">
            <thead>
                
                <tr>
                    <th>Name</th>
                    <th>Intake</th>
                    <th>Section</th>
                    <th>Department</th>
                    <th>Shift</th>
                    <th>Facebook</th>
                    <th>Phone</th>
                </tr>
            </thead>
            <tbody>
                
                {% for student in crs %}
                <tr>
                    <td>{{student.name}}</td>
                    <td>{{student.intake}}</td>
                    <td>{{student.section}}</td>
                    <td>{{student.department}}</td>
                    <td>{{student.shift}}</td>
                    <td class="text-left"><a href="{{student.facebook_profile}}">Open Link</a></td>
                    <td class="text-left">{% if student.contact_number %}{{student.contact_number}}{% else %} --------- {% endif %}</td>
                    
                </tr>


                {% endfor %}
               
                
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

templates/pages/assignments.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Assignments{% endblock title %}
{% block css %}
		
{% endblock css %}
{% block content %}
<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        {% if user.role == 'cr' %}
        <div class="text-right mb-4">
            <a href="{% url "add_assign" %}" class="btn btn-primary" >+ Add New Assignment or Notice of Report</a>
        </div>
        {% endif %}
    </div>
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Upcomming all Assignments and Reports or Tasks</div>

            </div>
            <div class="row gutters justify-content-center">
                <div class="col-xl-9 col-lg-9 col-md-10 col-sm-12">

                    <div class="timeline">
                        
                        {% for assign in assignments %}
                        <div class="timeline-row">
                        <a href="{% url "view_assign" assign.uid %}">
                                <div class="timeline-time">
                                    {{assign.date}}<small>12.00 AM</small>
                                </div>
                                <div class="timeline-content">
                                    <i class="icon-code"></i>
                                    <h4>{{assign.get_types_display}}</h4>
                                    <p>
                                        {{assign.assignment_title}}
                                    </p>
                                    
                                    <div class="">
                                        <span class="badge badge-pill badge-white">{{assign.course_code}}</span>
                                        <span class="badge badge-pill badge-white">{{assign.course_title}}</span>
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}
                        
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Two divide option of Lab report and Assignment lile col-md-6 and 6 -->
{% endblock content %}

templates/pages/exams.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}All Exams{% endblock title %}
{% block css %}
<!-- Datepicker css -->
<link rel="stylesheet" href="{% static "vendor/datepicker/css/classic.css" %}" />
<link rel="stylesheet" href="{% static "vendor/datepicker/css/classic.date.css" %}" />
{% endblock css %}
{% block content %}

<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="text-right mb-4">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addNewContact">Add New Exam</button>

            <!-- Modal -->
            <div class="modal fade" id="addNewContact" tabindex="-1" role="dialog" aria-labelledby="addNewContactLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">

                        <div class="modal-header">
                            <h5 class="modal-title" id="addNewContactLabel">New Coming exams</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        <div class="modal-body">
                            <form class="row gutters" method="POST" enctype="multipart/form-data" novalidate>
                                {% csrf_token %}
                                
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    {% for field in form %}
                                        {% if forloop.counter <= 3 %}
                                            <div class="form-group">
                                                <label for="contactName">{{field.label}}</label>
                                                {{field}}
                                            </div>
                                            {% if field.errors %}
                                            {% for error in field.errors %}
                                            <p class="danger">{{error}}</p>
                                            {% endfor %}
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                                    {% for field in form %}
                                        {% if forloop.counter > 3 and forloop.counter < 6 %}
                                            <div class="form-group">
                                                <label for="contactName">{{field.label}}</label>
                                                {{field}}
                                            </div>
                                            {% if field.errors %}
                                            {% for error in field.errors %}
                                            <p class="danger">{{error}}</p>
                                            {% endfor %}
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                    <div class="form-group">
                                        <label for="lbl">Details</label>
                                        {{form.detail}}
                                    </div>
                                </div>

                                  
                                
                            </div>
                            
                            <div class="modal-footer custom">
                                <div class="left-side">
                                    <button type="button" class="btn btn-link danger btn-block" data-dismiss="modal">Cancel</button>
                                </div>
                                <div class="divider"></div>
                                <div class="right-side">
                                    <button type="submit" class="btn btn-link success btn-block">Save</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Row end -->

<div class="row gutters">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Upcomming Class Tests, Exams</div>
            </div>
            <div class="card-body">
                
                <!-- Row starts -->
                <div class="row gutters">

                    {% for exam in all_exam %}
                    <div class="col-xl-2 col-lg-4 col-md-4 col-sm-4 col-12">
                        <div class="goal-card">
                            <h5>{{exam.course_name}}</h5>
                            <p class="percentage">{{exam.date}}</p>                            
                            <h4>{{exam.course_code}}</h4>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                <!-- Row ends -->

            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center success">
                        <li class="page-item disabled"><a class="page-link" href="#">
                            <i class="icon-chevron-left1"></i>First</a></li>
                        <li class="page-item"><a class="page-link" href="#">Prev</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                        <li class="page-item"><a class="page-link" href="#">Last <i class="icon-chevron-right1"></i></a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

{% block js %}
		<!-- Datepickers -->
<script src="{% static "vendor/datepicker/js/picker.js" %}"></script>
<script src="{% static "vendor/datepicker/js/picker.date.js" %}"></script>
<script src="{% static "vendor/datepicker/js/custom-picker.js" %}"></script>
{% endblock js %}

templates/pages/index.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block css %}
		
{% endblock css %}
{% block content %}

{% comment %} <div class="row mt-0">
    <div class="col-md-4 justify-content-center">
        <div class="card highlight pt-1 me-2">
            <h5> >> CSE317 start in 13:30 min | Latest Announced : </h5>
        </div>

    </div>
    <div class="col-md-8">
            <div class="card highlight pt-1 ">
                <h5>CSE 324(Database Lab) - Room:908 (B-2) | 12:45AM</h5>
            </div>
    </div>
</div> {% endcomment %}
<div class="row gutters mt-0">
</div>
<div class="row gutters">
    <div class="col-xl-10 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card highlight pt-1 mb-1 ">
                <h5>Running - {% if running_class %}CSE 324(Database Lab) - Room:908 (B-2) ({{running_class}}) {% endif %}| 
                    Next - {% if coming_class %}CSE320 Network Lab <span><i class="icon-clock"></i></span> ({{coming_class}})</h5>{% endif %}
            </div>
            {% if remain_task %}
            {% comment %} <div class="card highlight1 mt-0 pt-1">
                <marquee >
                    <h5>
                    {% for taskk in remain_task %}
                        {{taskk.assignment_title}} | 
                    {% endfor %}
                    </h5>
                </marquee>
            </div> {% endcomment %}
            {% endif %}
            <div class="card-body">
                
            
                <!-- Row starts -->
                
                <div class="card-title text-danger">Upcoming Exam</div>
                
                <div class="row gutters">
                    {% if exams %}
                   
                    {% for exam in exams %}
                    <div class="col-xl-2 col-lg-4 col-md-4 col-sm-4 col-12">
                        <div class="goal-card">
                            <h5>{{exam.course_name | truncatechars:"12"}}</h5>
                            <p class="percentage">{{exam.date}}</p>                            
                            <h4>{{exam.course_code}}</h4>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <h3>Have Fun Buddy. No exam in 10 Days</h3>
                    {% endif %}
                </div>
                <!-- Row ends -->

            </div>
        </div>
    </div>

    
    <div class="col-xl-2 col-lg-6 col-md-6 col-sm-6 col-12">

{% comment %} 
        <div class="launch-box h-180">
            <h6>Mid Term Exam</h6>
            <p>Friday, February 1</p>
            <h4 id="daysLeft">
                <div class="num">
                    50 <span class="text"> Days Left</span>
                </div>
            </h4>
        </div>

         {% endcomment %}
         
        <div class="risks-block high h-117">
            <i class="icon-warning1"></i>
            <div class="risk-details">
                <h2>{{remain_task.count}}</h2>
                <p>Pending Assignments or Reports<span>(Check the tasks)</span></p>
            </div>
        </div>
        
        <div class="risks-block low h-117">
            <i class="icon-{% if exams.count > 0 %}warning1{% else %}check_circle{% endif %}"></i>
            <div class="risk-details">
                <h2>{{exams.count}}</h2>
                <p>Upcomming Exams left<span>(Check exams)</span></p>
            </div>
        </div>
    </div>


</div>

<div class="row gutters justify-content-center">
    <h3 class="mb-2">TimeLine of the upcoming Week </h3>
    <div class="col-xl-9 col-lg-9 col-md-10 col-sm-12">

        <div class="timeline">
            
            {% for data in timeline %}
            <div class="timeline-row">
                
                    <div class="timeline-time">
                        {{data.date}}<small>12.00 AM</small>
                    </div>
                    <div class="timeline-content">
                        <i class="icon-code"></i>
                        <h4>{% if data.topic %}Exam{% else %}{{data.get_types_display}}{% endif %}</h4>
                        <p>
                            {% if data.details %}
                            {{data.details|safe|truncatewords:"25"}}
                            {% elif data.detail%}
                            {{data.detail|safe|truncatewords:"25"}}
                            {% endif %}
                        </p>
                        
                    </div>
                
            </div>
            {% endfor %}
            
        </div>
       
    </div>
</div>

<div class="row gutters">
    
    <div class="col-xl-9 col-lg-4 col-md-12 col-sm-12 col-12">
        {% include "pages/only_routine.html" %}
    </div>

    <div class="col-xl-3 col-lg-4 col-md-12 col-sm-12 col-12">
        <div class="card">
            <div class="card-header">
                <div class="card-title">Announcements</div>
            </div>
            <div class="card-body">
                <div class="customScroll5">
                    <ul class="user-messages">
                        {% for announce in announcements %}
                        <li class="clearfix bg-for-you rounded p-2">
                            <div class="customer"><img src="{{announce.who_posted.image.url}}" alt="pic"></div>
                            <div class="delivery-details ">
                                <span class="badge badge-primary">{{announce.who_posted}}</span>
                                <p>{{announce.announcement}}</p>
                        
                            </div>
                        </li>                       
                        {% endfor %}                        
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="card">
    <div class="card-header">
        <div class="card-title text-center">Students of Intake {{students.0.intake}} Section {{students.0.section.section}} </div>
    </div>
    <div class="row gutters">
    
        {% for student in students %}
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-4 col-12">
            <figure class="user-card">
                <figcaption>
                    <img src="{{student.image.url}}" alt="profile pic" class="profile">
                    <h5>{{student.name}}</h5>
                    
                    <ul class="list-group">
                        <li class="list-group-item">ID: {{student.personal_id}}</li>
                        <li class="list-group-item">{{student.contact_number}}</li>
                    </ul>
                </figcaption>
            </figure>
        </div>
        {% endfor %}
        
    </div>
</div>


{% endblock content %}

{% block js %}

<script src="{% static "vendor/slimscroll/slimscroll.min.js" %}"></script>
<script src="{% static "vendor/slimscroll/custom-scrollbar.js" %}"></script>

{% endblock js %}

templates/pages/only_form.html
<form method="POST" class="form-group" novalidate>
    {% csrf_token %}
    {% for field in form %}
    {{field.label}}
    {{field}}
    <br>
    {% if field.errors %}
    {% for error in field.errors %}
    <p class="text-danger">{{error}}</p>
    {% endfor %}
    {% endif %}            
    {% endfor %}
    <button type="submit" class=" btn btn-info btn-block"> Save</button>
</form>

templates/pages/student_approval.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Approve{% endblock title %}
{% block css %}
		
{% endblock css %}
{% block content %}

<!-- ADMIN or CR can be able to approve | BUT HERE CLASS CR QUERY GETTING NOT FOUND -->
{% if user.role == 'admin' or user.role == "cr" %}
{% include "pages/wait_student.html" %}
{% endif %}

{% endblock content %}

templates/pages/temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h2>
        {% for std in students %}
        {{std}}
        {% endfor %}
    </h2>

</body>
</html>

templates/pages/view_assignment.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Task Details{% endblock title %}
{% block css %}
		
{% endblock css %}
{% block content %}

<div class="row gutters justify-content-center">
    
    <div class="col-xl-5 col-lg-5 col-md-6 col-sm-8 col-12">
        <div class="subscribe-form">
            <h4 class="text-center mb-3 text-info">{{task.assignment_title}}</h4>
            {{task.detail}}
        </div>

    </div>
</div>

{% endblock content %}

templates/pages/waiting.html
{% extends "auths/base.html" %}
{% load static %}
{% block title %}Pending{% endblock title %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 text-center">
            <h2 class="mb-4 text-danger">Please wait while your account getting verify</h2>
            <div class="spinner-grow text-dark" role="status">
                <span class="sr-only"></span>
            </div>
            <div class="spinner-grow text-info" role="status">
                <span class="sr-only"></span>
            </div>
            <div class="spinner-grow text-warning" role="status">
                <span class="sr-only"></span>
            </div>
            <div class="mt-3">
                <a class="btn btn-primary" href="{% url "user_logout" %}">Logout</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}